[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Timeline"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 3

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 4

[[main]]
  parent = "gallery"
  name = "Cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"

[[main]]
  identifier = "presentation"
  name = "PPT"
  url = "presentation"
  weight = 5

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 6

# [[main]]
#   identifier = "publication"
#   name = "Pub"
#   url = "publication"
#   weight = 7
