[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Timeline"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery/photo"
  weight = 3

[[main]]
  identifier = "Projects"
  name = "Projects"
  url = "showcase"
  weight = 4

# [[main]]
#  identifier = "presentation"
#  name = "PPT"
#  url = "presentation"
#  weight = 5 

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 6

